apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpdesk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helpdesk.name" . }}
    helm.sh/chart: {{ include "helpdesk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  local_config.py: |
{{ .Values.config | indent 4 }}
