apiVersion: v1
kind: Secret
metadata:
  name: {{ include ".Values.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- with .Values.useConfigDir }}
data: {{ (.Files.Glob "helpdesk/*").AsSecrets }}
{{- else }}
data: {{ .Values.config | b64enc }}
{{- end }}
