# Default values for helpdesk chart.

replicaCount: 2

image:
  repository: tclh123/helpdesk
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - helpdesk.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

config: |
  # coding: utf-8
  # vi: ft=python
  
  
  DEBUG = DEVELOP_MODE = True
  
  SENTRY_DSN = ''
  
  SESSION_SECRET_KEY = 'NVzLYJSMyw'
  
  SESSION_TTL = 24 * 3600
  
  SYSTEM_USER = 'admin'
  SYSTEM_USER_PASSWORD = 'admin'
  
  ADMIN_ROLES = ['admin', 'system_admin']
  
  PARAM_FILLUP = {
      # 'reason': 'hehe',
      'ldap_id': lambda provider: provider.user,
  }
  
  DATABASE_URL = 'mysql://helpdesk:he1pde2k@helpdesk-mysql/helpdesk'
  
  PROVIDER = 'st2'
  
  ST2_BASE_URL = 'https://st2.example.com'
  ST2_API_URL = 'https://st2.example.com/api'
  ST2_AUTH_URL = 'https://st2.example.com/auth'
  ST2_STREAM_URL = 'https://st2.example.com/stream'
  
  ST2_EXECUTION_RESULT_URL_PATTERN = ST2_BASE_URL + '/#/code/result/{execution_id}'
  
  ST2_API_KEY = None
  
  ST2_CACERT = None
  
  ST2_DEFAULT_PACK = ''
  
  ST2_WORKFLOW_RUNNER_TYPES = [
      'action-chain',
      'mistral-v2',
      'orquesta'
  ]
  
  ST2_TOKEN_TTL = 24 * 3600
  
  # LDAP
  
  DEFAULT_EMAIL_DOMAIN = 'example.com'
  # base url will be used by notifications to show web links
  DEFAULT_BASE_URL = 'https://example.com'
  FORCE_HTTPS = False
  ADMIN_EMAIL_ADDRS = 'admin@example.com,ops@example.com'
  FROM_EMAIL_ADDR = 'helpdesk@example.com'
  
  NOTIFICATION_TITLE_PREFIX = '[helpdesk] '
  
  NO_AUTH_TARGET_OBJECTS = ['ldap_pass_reset']
  
  URL_RESET_PASSWORD = ''
  
  AUTO_APPROVAL_TARGET_OBJECTS = []
  
  TICKETS_PER_PAGE = 50
  
  
  def avatar_url_func(ldap_id):
      import hashlib
      GRAVATAR_URL = '//www.gravatar.com/avatar/%s'
      email = '%s@example.com' % ldap_id
      return GRAVATAR_URL % hashlib.md5(email.encode('utf-8').lower()).hexdigest()
  
  
  # Action Tree Config
  # action name, description/tips, st2 pack/action
  
  ACCOUNT_SUBTREE = ['账号相关', [
      # ['', '', ''],
      ['申请服务器账号/重置密码', '申请 ssh 登录服务器的账号，或者重置密码', ''],
      ['申请创建分布式文件系统用户目录', '跑分布式计算脚本常用的前置条件', ''],
      ['申请加入用户组', '', ''],
      ]]
  
  PACKAGE_SUBTREE = ['包管理相关', [
      # ['', '', ''],
      ['查询服务器上包版本', '可查询的信息有 ebuild 版本号、编译/部署时间，VCS 版本', ''],
      ['在部分机器上用 nobinpkg 测试包', '常用于在部分服务器上测试新版本，观察可用性与稳定性时', ''],
      ['build binpkg 并全量更新', '常用于使用 nobinpkg 测试完毕，可以上线到生产环境时', ''],
      ['将已有的 binpkg 装到指定机器', '常用于将当前稳定版本安装到之前并未部署此包的机器上时', ''],
      ['仅 build binpkg 而不安装', '此功能并不常用，请慎用，仅用于为即将被部署的包打 binpkg 时', ''],
      ['使用现有的 binpkg 全量更新', '常用于已在 binhost 上生成 binpkg 的大型软件包', ''],
      ['回滚包到指定 VCS 版本', '常用于将 9999 包回滚到某个 VCS 版本', ''],
      ]]
  
  ACTION_TREE_CONFIG = ['功能导航', [ACCOUNT_SUBTREE, PACKAGE_SUBTREE]]

global:
  sql:
    password: "he1pde2k"

mysql:
  install: true
  imageTag: "5.7.14"
  ## Specify password for root user
  ##
  ## Default: random 10 character string
  mysqlRootPassword: "ro0t_he1pde2k"

  ## Create a database user
  ##
  mysqlUser: "helpdesk"
  ## Default: random 10 character string
  mysqlPassword: "he1pde2k"

  ## Allow unauthenticated access, uncomment to enable
  ##
  # mysqlAllowEmptyPassword: true

  ## Create a database
  ##
  mysqlDatabase: "helpdesk"

  ## Persist data to a persistent volume
  persistence:
    enabled: true
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi
    annotations: {}

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  # Custom mysql configuration files used to override default mysql settings
  configurationFiles:
    mysql.cnf: |-
      [mysqld]
      character-set-server = utf8mb4
      collation-server = utf8mb4_unicode_ci
      
      [mysql]
      default-character-set = utf8mb4
      
      [client]
      default-character-set = utf8mb4

  # Custom mysql init SQL files used to initialize the database
  initializationFiles: {}
  #  first-db.sql: |-
  #    CREATE DATABASE IF NOT EXISTS first DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
  #  second-db.sql: |-
  #    CREATE DATABASE IF NOT EXISTS second DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


